name: SonarCloud Multi-Repo Analysis

on:
  workflow_dispatch:  # Manually trigger the workflow
  schedule:           # On a schedule
    - cron: '0 16 * * 4'

jobs:
  sonarcloud-analysis:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - githubOrg: 'cortezaproject'
            githubRepo: 'corteza'
#          - githubOrg: 'org1'       # GitHub organization name for the repo
#            githubRepo: 'repo1'     # GitHub repository name
    steps:
      - name: Checkout ${{ matrix.config.githubOrg }}/${{ matrix.config.githubRepo }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
          repository: '${{ matrix.config.githubOrg }}/${{ matrix.config.githubRepo }}'
          path: '${{ matrix.config.githubOrg }}/${{ matrix.config.githubRepo }}'  # Checkout each repo in a unique path

      - name: Run SonarCloud Analysis @ ${{ matrix.config.githubOrg }}/${{ matrix.config.githubRepo }}
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_WORKSPACE: '${{ matrix.config.githubOrg }}/${{ matrix.config.githubRepo }}'  # Set the workspace path for each repo
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
